// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSampleWebjob.Models
{
    public partial class Book
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string genre { get; set; }
        public string description { get; set; }
        public string isbn { get; set; }
        public string image { get; set; }
        public string published { get; set; }
        public string publisher { get; set; }
    }
}